# Generated by Django 3.2.13 on 2022-06-12 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgbot', '0003_rm_unused_fields'),
        ('arcgis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_time', models.DateTimeField(blank=True, null=True, verbose_name='Время заказа')),
                ('confirmed_time', models.DateTimeField(blank=True, null=True, verbose_name='Согласована')),
                ('picked_time', models.DateTimeField(blank=True, null=True, verbose_name='Курьер забрал заказ')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало выполнения')),
                ('done_time', models.DateTimeField(blank=True, null=True, verbose_name='Сделано')),
                ('delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Доставлено')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Информация')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий')),
                ('state', models.IntegerField(choices=[(None, 'Новый заказ'), ('NEW', 'Новый заказ'), ('CONFIRMED', 'Заказ одобрен, ожидание курьера'), ('RECEIVING', 'Курьер в пути'), ('PICKED', 'Курьер забрал заказ'), ('EXECUTING', 'Выполнение заказа'), ('DONE', 'Заказ выполнен'), ('WAITING_FOR_DELIVERY', 'Ожидание доставки'), ('DELIVERING', 'Курьер в процессе отгрузки'), ('COMPLETED', 'Заказ выполнен'), ('CANCELED', 'Заказ отменен')], default='NEW', max_length=30, verbose_name='Статус')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='tgbot.user', verbose_name='Курьер')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcgis.arcgis', verbose_name='Локация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tgbot.user', verbose_name='Клиент')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(upload_to='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
