# Generated by Django 3.2.13 on 2022-06-24 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arcgis', '0001_initial'),
        ('tgbot', '0003_rm_unused_fields'),
        ('order', '0003_alter_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='tgbot.user', verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arcgis.arcgis', verbose_name='Локация'),
        ),
    ]
