# Generated by Django 3.2.13 on 2022-07-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_user_is_courier'),
        ('order', '0005_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tgbot.location', verbose_name='Локация'),
        ),
    ]
